# Site settings
title: Matt Born Writes
email: hey@mattborn.com
description: "Matt Born’s personal blog about design, development, ideas, etc."
baseurl: "/writes"
url: "http://mattborn.com"
twitter_username: matthewcyan
github_username: mattborn

# Build settings
markdown: kramdown
permalink: :title